### ISSUE TITLE
Version dart resolve fail

### ISSUE THREAD

**Issue by vuldk94** [doannc2212/vnpay_client#2]
vnpay_client >=0.0.2 which requires SDK version >=3.1.3 <4.0.0, version solving failed

- Hiện tại mình thấy bạn đang để SDK cho Lib hơi cao, mình nghĩ nên chỉ để tầm 3.0 đổ lên thôi ạ. Vì giờ nhiều project cũng chưa update lên ver 3.1.3 đổ lên nên khó tích hợp vào app

**Comment by doannc2212** [comment]
Cảm ơn bạn đã góp ý, mình sẽ chỉnh lại version.

**Comment by doannc2212** [comment]
https://github.com/doannc2212/vnpay_client/blob/004e505c16e4b94f0aeb40a42a7292f8cdb88981/pubspec.yaml#L7
